# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 908)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(390, 120, 352, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.c1_cost = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c1_cost.setFont(font)
        self.c1_cost.setStyleSheet("color:rgb(0, 85, 255)")
        self.c1_cost.setObjectName("c1_cost")
        self.gridLayout.addWidget(self.c1_cost, 1, 1, 1, 1)
        self.c1_attack = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c1_attack.setFont(font)
        self.c1_attack.setStyleSheet("color:rgb(170, 85, 255)")
        self.c1_attack.setObjectName("c1_attack")
        self.gridLayout.addWidget(self.c1_attack, 1, 2, 1, 1)
        self.c1_health = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c1_health.setFont(font)
        self.c1_health.setStyleSheet("color:rgb(245, 0, 0)")
        self.c1_health.setObjectName("c1_health")
        self.gridLayout.addWidget(self.c1_health, 1, 3, 1, 2)
        self.c1_type = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1_type.setObjectName("c1_type")
        self.gridLayout.addWidget(self.c1_type, 3, 1, 1, 1)
        self.c1_race = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1_race.setObjectName("c1_race")
        self.gridLayout.addWidget(self.c1_race, 1, 5, 1, 1)
        self.c1_rarity = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1_rarity.setObjectName("c1_rarity")
        self.gridLayout.addWidget(self.c1_rarity, 3, 2, 1, 1)
        self.c1_cardClass = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1_cardClass.setObjectName("c1_cardClass")
        self.gridLayout.addWidget(self.c1_cardClass, 3, 5, 1, 1)
        self.c1_set = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1_set.setObjectName("c1_set")
        self.gridLayout.addWidget(self.c1_set, 3, 3, 1, 2)
        self.c1_text = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.c1_text.setObjectName("c1_text")
        self.gridLayout.addWidget(self.c1_text, 2, 1, 1, 5)
        self.c1_name = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c1_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.c1_name.setObjectName("c1_name")
        self.gridLayout.addWidget(self.c1_name, 0, 1, 1, 2)
        self.c1_id = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1_id.setObjectName("c1_id")
        self.gridLayout.addWidget(self.c1_id, 0, 5, 1, 1)
        self.c1_table = QtWidgets.QTableView(self.centralwidget)
        self.c1_table.setGeometry(QtCore.QRect(10, 40, 321, 811))
        self.c1_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.c1_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.c1_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.c1_table.setSortingEnabled(True)
        self.c1_table.setObjectName("c1_table")
        self.c1_prev = QtWidgets.QPushButton(self.centralwidget)
        self.c1_prev.setGeometry(QtCore.QRect(420, 40, 91, 41))
        self.c1_prev.setObjectName("c1_prev")
        self.c1_next = QtWidgets.QPushButton(self.centralwidget)
        self.c1_next.setGeometry(QtCore.QRect(590, 40, 91, 41))
        self.c1_next.setObjectName("c1_next")
        self.c2_table = QtWidgets.QTableView(self.centralwidget)
        self.c2_table.setGeometry(QtCore.QRect(830, 30, 341, 821))
        self.c2_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.c2_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.c2_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.c2_table.setSortingEnabled(True)
        self.c2_table.setObjectName("c2_table")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(390, 290, 352, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.c2_cost = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c2_cost.setFont(font)
        self.c2_cost.setStyleSheet("color:rgb(0, 85, 255)")
        self.c2_cost.setObjectName("c2_cost")
        self.gridLayout_2.addWidget(self.c2_cost, 1, 1, 1, 1)
        self.c2_attack = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c2_attack.setFont(font)
        self.c2_attack.setStyleSheet("color:rgb(170, 85, 255)")
        self.c2_attack.setObjectName("c2_attack")
        self.gridLayout_2.addWidget(self.c2_attack, 1, 2, 1, 1)
        self.c2_health = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c2_health.setFont(font)
        self.c2_health.setStyleSheet("color:rgb(245, 0, 0)")
        self.c2_health.setObjectName("c2_health")
        self.gridLayout_2.addWidget(self.c2_health, 1, 3, 1, 2)
        self.c2_type = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.c2_type.setObjectName("c2_type")
        self.gridLayout_2.addWidget(self.c2_type, 3, 1, 1, 1)
        self.c2_race = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.c2_race.setObjectName("c2_race")
        self.gridLayout_2.addWidget(self.c2_race, 1, 5, 1, 1)
        self.c2_rarity = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.c2_rarity.setObjectName("c2_rarity")
        self.gridLayout_2.addWidget(self.c2_rarity, 3, 2, 1, 1)
        self.c2_cardClass = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.c2_cardClass.setObjectName("c2_cardClass")
        self.gridLayout_2.addWidget(self.c2_cardClass, 3, 5, 1, 1)
        self.c2_set = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.c2_set.setObjectName("c2_set")
        self.gridLayout_2.addWidget(self.c2_set, 3, 3, 1, 2)
        self.c2_text = QtWidgets.QTextBrowser(self.gridLayoutWidget_2)
        self.c2_text.setObjectName("c2_text")
        self.gridLayout_2.addWidget(self.c2_text, 2, 1, 1, 5)
        self.c2_name = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.c2_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.c2_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.c2_name.setObjectName("c2_name")
        self.gridLayout_2.addWidget(self.c2_name, 0, 1, 1, 2)
        self.c2_id = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.c2_id.setObjectName("c2_id")
        self.gridLayout_2.addWidget(self.c2_id, 0, 5, 1, 1)
        self.c2_prev = QtWidgets.QPushButton(self.centralwidget)
        self.c2_prev.setGeometry(QtCore.QRect(430, 550, 91, 41))
        self.c2_prev.setObjectName("c2_prev")
        self.c2_next = QtWidgets.QPushButton(self.centralwidget)
        self.c2_next.setGeometry(QtCore.QRect(600, 550, 91, 41))
        self.c2_next.setObjectName("c2_next")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(510, 460, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(460, 710, 75, 23))
        self.save.setObjectName("save")
        self.load = QtWidgets.QPushButton(self.centralwidget)
        self.load.setGeometry(QtCore.QRect(590, 710, 75, 23))
        self.load.setObjectName("load")
        self.c1_sbid = QtWidgets.QPushButton(self.centralwidget)
        self.c1_sbid.setGeometry(QtCore.QRect(10, 10, 101, 23))
        self.c1_sbid.setObjectName("c1_sbid")
        self.c1_sbre = QtWidgets.QPushButton(self.centralwidget)
        self.c1_sbre.setGeometry(QtCore.QRect(190, 10, 121, 23))
        self.c1_sbre.setObjectName("c1_sbre")
        self.c2_sbid = QtWidgets.QPushButton(self.centralwidget)
        self.c2_sbid.setGeometry(QtCore.QRect(840, 0, 101, 23))
        self.c2_sbid.setObjectName("c2_sbid")
        self.c2_sbre = QtWidgets.QPushButton(self.centralwidget)
        self.c2_sbre.setGeometry(QtCore.QRect(990, 0, 121, 23))
        self.c2_sbre.setObjectName("c2_sbre")
        self.sub = QtWidgets.QPushButton(self.centralwidget)
        self.sub.setGeometry(QtCore.QRect(620, 460, 41, 41))
        self.sub.setObjectName("sub")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(370, 270, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1186, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.spinBox.valueChanged['int'].connect(self.spinBox.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.c1_cost.setText(_translate("MainWindow", "c1_cost"))
        self.c1_attack.setText(_translate("MainWindow", "c1_att"))
        self.c1_health.setText(_translate("MainWindow", "c1_health"))
        self.c1_type.setText(_translate("MainWindow", "c1_type"))
        self.c1_race.setText(_translate("MainWindow", "c1_race"))
        self.c1_rarity.setText(_translate("MainWindow", "c1_rarity"))
        self.c1_cardClass.setText(_translate("MainWindow", "c1_cardClass"))
        self.c1_set.setText(_translate("MainWindow", "c1_set"))
        self.c1_name.setText(_translate("MainWindow", "c1_name"))
        self.c1_id.setText(_translate("MainWindow", "c1_id"))
        self.c1_prev.setText(_translate("MainWindow", "c1_prev"))
        self.c1_next.setText(_translate("MainWindow", "c1_next"))
        self.c2_cost.setText(_translate("MainWindow", "c1_cost"))
        self.c2_attack.setText(_translate("MainWindow", "c1_att"))
        self.c2_health.setText(_translate("MainWindow", "c1_health"))
        self.c2_type.setText(_translate("MainWindow", "c1_type"))
        self.c2_race.setText(_translate("MainWindow", "c1_race"))
        self.c2_rarity.setText(_translate("MainWindow", "c1_rarity"))
        self.c2_cardClass.setText(_translate("MainWindow", "c1_cardClass"))
        self.c2_set.setText(_translate("MainWindow", "c1_set"))
        self.c2_name.setText(_translate("MainWindow", "c1_name"))
        self.c2_id.setText(_translate("MainWindow", "c2_id"))
        self.c2_prev.setText(_translate("MainWindow", "c2_prev"))
        self.c2_next.setText(_translate("MainWindow", "c2_next"))
        self.save.setText(_translate("MainWindow", "save"))
        self.load.setText(_translate("MainWindow", "load"))
        self.c1_sbid.setText(_translate("MainWindow", "sort by id"))
        self.c1_sbre.setText(_translate("MainWindow", "sort by relat"))
        self.c2_sbid.setText(_translate("MainWindow", "sort by id"))
        self.c2_sbre.setText(_translate("MainWindow", "sort by relat"))
        self.sub.setText(_translate("MainWindow", "sub"))

